# ~/alacritty.yaml

env:
  TERM: xterm-256color

window:
  padding:
    x: 5

  title: Alacritty

scrolling:
  history: 100000

font:
  normal:
    family: Roboto Mono for Powerline
    style: Regular
  bold:
    family: Roboto Mono for Powerline
    style: Bold
  italic:
    family: Roboto Mono for Powerline
    style: Italic
  bold_italic:
    family: Roboto Mono for Powerline
    style: Bold Italic
  size: 12.0

shell:
  program: '/usr/local/bin/nu'

# Colors
colors:
  # Default colors
  primary:
    background: '0x1E1E3F'
    foreground: '0xC9C8FF'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1E3F'
    cursor: '0xFAD000'

  # Normal colors
  normal:
    black: '0x000000'
    red: '0xEC3A37'
    green: '0x75e44c'
    yellow: '0xFAD000'
    blue: '0x6943FF'
    magenta: '0xFF2C70'
    cyan: '0x80FCFF'
    white: '0xFFFFFF'

  # Bright colors
  bright:
    black: '0x5C5C61'
    red: '0xEC3A37'
    green: '0x3AD900'
    yellow: '0xFAD000'
    blue: '0x6943FF'
    magenta: '0xFB94FF'
    cyan: '0x80FCFF'
    white: '0x2D2B55'

selection:
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

key_bindings:
    # Spawn instance
    - { key: N,         mods: Command,      action: SpawnNewInstance }
    # \i
    - { key: B,         mods: Alt,          chars: "\x5c" }
    # |
    - { key: L,         mods: Alt,          chars: "\x7c" }
    # {}
    - { key: LBracket,  mods: Alt,          chars: "\x7b" }
    - { key: RBracket,  mods: Alt,          chars: "\x7d" }
    # []
    - { key: LBracket,  mods: Alt|Shift,    chars: "\x5b" }
    - { key: RBracket,  mods: Alt|Shift,    chars: "\x5d" }
    # Move cursor to previous/next word
    - { key: Left,      mods: Shift,        chars: "\x1b[1;6D" }
    - { key: Right,     mods: Shift,        chars: "\x1b[1;6C" }
