env:
  TERM: xterm-256color

font:
  normal:
    family: Roboto Mono for Powerline
    style: Regular
  bold:
    family: Roboto Mono for Powerline
    style: Bold
  italic:
    family: Roboto Mono for Powerline
    style: Italic
  bold_italic:
    family: Roboto Mono for Powerline
    style: Bold Italic
  size: 9.0

scrolling:
  history: 100000

background_opacity: 0.95

colors:
  # Default colors
  primary:
    background: '0x1E1E3F'
    foreground: '0xC9C8FF'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1E3F'
    cursor: '0xFAD000'

  # Normal colors
  normal:
    black: '0x000000'
    red: '0xEC3A37'
    green: '0x75e44c'
    yellow: '0xFAD000'
    blue: '0x6943FF'
    magenta: '0xFF2C70'
    cyan: '0x80FCFF'
    white: '0xFFFFFF'

  # Bright colors
  bright:
    black: '0x5C5C61'
    red: '0xEC3A37'
    green: '0x3AD900'
    yellow: '0xFAD000'
    blue: '0x6943FF'
    magenta: '0xFB94FF'
    cyan: '0x80FCFF'
    white: '0x2D2B55'

selection:
  save_to_clipboard: true
